"""categories table changed

Revision ID: 0a438c2eba05
Revises: 65944d52d499
Create Date: 2020-11-07 19:41:19.226400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a438c2eba05'
down_revision = '65944d52d499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('product_category', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('service_category', sa.Integer(), nullable=True))
    op.add_column('service', sa.Column('service_category', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'service_category')
    op.drop_column('categories', 'service_category')
    op.drop_column('categories', 'product_category')
    # ### end Alembic commands ###
