"""setting model added

Revision ID: 3606dd8884b1
Revises: ed3dd243bde3
Create Date: 2020-12-19 12:57:43.647043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3606dd8884b1'
down_revision = 'ed3dd243bde3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('setting_type', sa.String(length=50), nullable=False),
    sa.Column('setting_description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('setting_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
