"""initial migration

Revision ID: 42efccc352cd
Revises: 
Create Date: 2021-03-19 21:48:21.317941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42efccc352cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('cat_title', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('cat_id')
    )
    op.create_table('post',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('post_title', sa.String(length=200), nullable=False),
    sa.Column('post_description', sa.Text(), nullable=True),
    sa.Column('post_image', sa.Text(), nullable=True),
    sa.Column('post_category', sa.Integer(), nullable=True),
    sa.Column('is_admin_post', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('is_admin', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('post')
    op.drop_table('categories')
    # ### end Alembic commands ###
