"""models are readyy

Revision ID: 65944d52d499
Revises: 
Create Date: 2020-11-07 18:56:40.241329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65944d52d499'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('cat_id', sa.Integer(), nullable=False),
    sa.Column('cat_title', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('cat_id')
    )
    op.create_table('customers',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_image', sa.Text(), nullable=True),
    sa.Column('customer_review', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('logos',
    sa.Column('logo_id', sa.Integer(), nullable=False),
    sa.Column('logo_image', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('logo_id')
    )
    op.create_table('partners',
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('partner_title', sa.String(length=200), nullable=False),
    sa.Column('partner_image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('partner_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_title', sa.String(length=200), nullable=False),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('product_price', sa.Float(), nullable=False),
    sa.Column('product_image', sa.Text(), nullable=True),
    sa.Column('product_category', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('service',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('service_title', sa.String(length=200), nullable=False),
    sa.Column('service_description', sa.Text(), nullable=True),
    sa.Column('service_charges', sa.Float(), nullable=False),
    sa.Column('service_image', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('sliders',
    sa.Column('slider_id', sa.Integer(), nullable=False),
    sa.Column('slider_title', sa.Text(), nullable=True),
    sa.Column('slider_image', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('slider_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('sliders')
    op.drop_table('service')
    op.drop_table('product')
    op.drop_table('partners')
    op.drop_table('logos')
    op.drop_table('customers')
    op.drop_table('categories')
    # ### end Alembic commands ###
