"""social media links model added

Revision ID: ed3dd243bde3
Revises: 6eae6db28e8b
Create Date: 2020-11-22 14:52:21.770544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed3dd243bde3'
down_revision = '6eae6db28e8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_media_links',
    sa.Column('sm_id', sa.Integer(), nullable=False),
    sa.Column('fb_link', sa.String(length=200), nullable=True),
    sa.Column('twitter_link', sa.String(length=200), nullable=True),
    sa.Column('instagram_link', sa.String(length=200), nullable=True),
    sa.Column('google_plus_link', sa.String(length=200), nullable=True),
    sa.Column('linkedin_link', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('sm_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_media_links')
    # ### end Alembic commands ###
